# Generated by Django 5.2.4 on 2025-08-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_add_organization_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
