# Generated by Django 5.2.4 on 2025-08-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_organization_remove_customer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
