# Generated by Django 5.2.4 on 2025-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='lock_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
