# Generated by Django 5.2.4 on 2025-08-16 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('customer', '0009_organization_lock_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('line_of_credit', 'Line of Credit'), ('merchant', 'Merchant Account'), ('other', 'Other')], help_text='Type of financial account', max_length=20)),
                ('account_name', models.CharField(help_text="Friendly name for this account (e.g., 'Main Checking', 'Company Visa')", max_length=255)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank or financial institution', max_length=255)),
                ('routing_number', models.CharField(blank=True, help_text='Bank routing number (for ACH/wire transfers)', max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='Bank account or card number (store securely)', max_length=50)),
                ('card_network', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], help_text='Credit card network (for credit/debit cards)', max_length=20)),
                ('card_last_four', models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4)),
                ('card_expiry_month', models.IntegerField(blank=True, help_text='Card expiry month (1-12)', null=True)),
                ('card_expiry_year', models.IntegerField(blank=True, help_text='Card expiry year (YYYY)', null=True)),
                ('cardholder_name', models.CharField(blank=True, help_text='Name on the card', max_length=255)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for credit cards/lines of credit', max_digits=12, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Current balance (optional, for tracking)', max_digits=12, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=20)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for this type')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(blank=True, help_text='Linked general ledger account for accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='accounting.ledgeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='customer.organization')),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'ordering': ['-is_primary', 'account_type', 'account_name'],
                'indexes': [models.Index(fields=['organization', 'account_type', 'is_active'], name='customer_fi_organiz_84ac08_idx')],
            },
        ),
    ]
