# Generated by Django 5.2.4 on 2025-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_add_financial_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/'),
        ),
    ]
