# Generated by Django 5.2.4 on 2025-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serial_number_managed',
            field=models.BooleanField(default=False, help_text='Whether this product requires serial number tracking'),
        ),
    ]
