# Generated by Django 5.2.4 on 2025-08-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the option (e.g., Size, Color)', max_length=100)),
                ('description', models.CharField(help_text='Value of the option (e.g., Large, Red)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value of the option item (e.g., Large, Red)', max_length=20)),
                ('ordering', models.IntegerField(default=0, help_text='Display order of this option item')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_name', models.ForeignKey(help_text='The option this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productoptionname')),
            ],
            options={
                'verbose_name': 'Product Option Item',
                'verbose_name_plural': 'Product Option Items',
                'ordering': ['ordering', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_ordering', models.IntegerField(default=0, help_text='Display order of this option for the product')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active for the product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.product')),
                ('option_name', models.ForeignKey(help_text='The name of the option (e.g., Size, Color)', on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='product.productoptionname')),
            ],
        ),
    ]
