# Generated by Django 5.2.4 on 2025-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productoptionname_productoptionitem_productoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoptionname',
            options={'ordering': ['name'], 'verbose_name': 'Product Option Name', 'verbose_name_plural': 'Product Option Names'},
        ),
        migrations.AddField(
            model_name='productoptionname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productoptionname',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this option type'),
        ),
        migrations.AlterField(
            model_name='productoptionname',
            name='name',
            field=models.CharField(help_text='Name of the option (e.g., Size, Color)', max_length=100, unique=True),
        ),
    ]
