# Generated by Django 5.2.4 on 2025-08-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_unique_slug'),
        ('purchases', '0002_remove_purchaseorder_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='purchases.supplier'),
        ),
    ]
