# Generated by Django 5.2.4 on 2025-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/'),
        ),
    ]
