# Generated by Django 5.2.4 on 2025-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price_disclosed',
            field=models.BooleanField(default=False, help_text="Whether this product's price is disclosed to customers"),
        ),
    ]
