# Generated by Django 5.2.4 on 2025-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_is_price_disclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_member_only',
            field=models.BooleanField(default=False, help_text='Whether this product is only available to members'),
        ),
        migrations.AddField(
            model_name='product',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Member price for this product', max_digits=10, null=True),
        ),
    ]
