# Generated by Django 5.2.4 on 2025-08-07 17:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_remove_unique_slug'),
        ('sales', '0007_make_payment_customer_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready for Shipping'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, help_text='Department responsible for fulfillment', max_length=100)),
                ('internal_notes', models.TextField(blank=True)),
                ('production_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='sales.invoice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('needed_by', models.DateField()),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('purchase_order_number', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(help_text='Reason for supply request')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests_created', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='factory.workorder')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('carrier', models.CharField(choices=[('ups', 'UPS'), ('fedex', 'FedEx'), ('usps', 'USPS'), ('dhl', 'DHL'), ('internal', 'Internal Delivery'), ('pickup', 'Customer Pickup'), ('other', 'Other')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('service_type', models.CharField(blank=True, help_text='e.g., Ground, 2-Day, Overnight', max_length=100)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready to Ship'), ('picked_up', 'Picked Up by Carrier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='preparing', max_length=20)),
                ('ship_to_name', models.CharField(max_length=200)),
                ('ship_to_company', models.CharField(blank=True, max_length=200)),
                ('ship_to_address_line1', models.CharField(max_length=255)),
                ('ship_to_address_line2', models.CharField(blank=True, max_length=255)),
                ('ship_to_city', models.CharField(max_length=100)),
                ('ship_to_state', models.CharField(max_length=50)),
                ('ship_to_postal_code', models.CharField(max_length=20)),
                ('ship_to_country', models.CharField(default='US', max_length=2)),
                ('ship_to_phone', models.CharField(blank=True, max_length=20)),
                ('ship_to_email', models.EmailField(blank=True, max_length=254)),
                ('number_of_packages', models.IntegerField(default=1)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in pounds', max_digits=10, null=True)),
                ('package_dimensions', models.CharField(blank=True, help_text='L x W x H in inches', max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('packing_list_generated', models.BooleanField(default=False)),
                ('shipping_label_generated', models.BooleanField(default=False)),
                ('customs_forms_required', models.BooleanField(default=False)),
                ('customs_forms_completed', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('delivery_signature', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_shipments', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='factory.workorder')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Inventory Allocated'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('warehouse_location', models.CharField(blank=True, max_length=100)),
                ('bin_location', models.CharField(blank=True, max_length=50)),
                ('allocated_date', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quality_check_notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_items', to=settings.AUTH_USER_MODEL)),
                ('allocated_inventory', models.ManyToManyField(blank=True, related_name='fulfillment_allocations', to='product.inventory')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_items', to=settings.AUTH_USER_MODEL)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='sales.invoiceitem')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='factory.workorder')),
            ],
            options={
                'ordering': ['work_order', 'invoice_item'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='factory_wor_status_2713ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['invoice'], name='factory_wor_invoice_182993_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['status', 'urgency'], name='factory_sup_status_2069cc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['product'], name='factory_sup_product_c59eca_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='factory_shi_status_8f3d98_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='factory_shi_trackin_5508d2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['work_order'], name='factory_shi_work_or_eaf107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fulfillmentitem',
            unique_together={('work_order', 'invoice_item')},
        ),
    ]
