# Generated by Django 5.2.4 on 2025-08-07 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('purchases', '0002_remove_purchaseorder_shipping_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('manager', 'Factory Manager'), ('supervisor', 'Supervisor'), ('worker', 'Factory Worker'), ('quality', 'Quality Control'), ('shipping', 'Shipping Staff')], default='worker', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('can_approve_orders', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_create_shipments', models.BooleanField(default=False)),
                ('can_approve_supply_requests', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_users', to='purchases.supplier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory User',
                'verbose_name_plural': 'Factory Users',
                'ordering': ['supplier', 'user__first_name', 'user__last_name'],
            },
        ),
    ]
