# Generated by Django 5.2.4 on 2025-08-01 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0001_initial'),
        ('email_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('marketing', 'Marketing Campaign'), ('periodic', 'Periodic Campaign')], default='marketing', max_length=20),
        ),
        migrations.CreateModel(
            name='PeriodicCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_link', models.URLField(help_text='Base URL for the campaign', max_length=500)),
                ('target_link_parameter', models.CharField(blank=True, help_text='URL parameters to append (e.g., ?utm_source=email&utm_campaign=periodic)', max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_campaigns', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodic_campaigns', to='email_templates.emailtemplate')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodic_campaigns', to='email_campaign.targetgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('recipients_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('email_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_campaign.emailcampaign')),
                ('periodic_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_campaign.periodiccampaign')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
