# Generated by Django 5.2.4 on 2025-08-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0002_emailcampaign_campaign_type_periodiccampaign_and_more'),
        ('email_templates', '0002_emailtemplatevariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_campaigns', to='email_templates.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
