# Generated by Django 5.2.4 on 2025-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_location', models.CharField(choices=[('header', 'Header'), ('side_left', 'Side Left'), ('side_right', 'Side Right'), ('footer', 'Footer'), ('content', 'Content')], max_length=30)),
                ('menu_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('menu_path_info', models.CharField(max_length=255)),
                ('order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
