# Generated by Django 5.2.4 on 2025-08-03 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_address_line1',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_address_line2',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_phone',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount_percent',
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('KOR', 'Korea')], default='USA', max_length=100)),
                ('internal_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchases.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_contacts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='purchases.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='supplier_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_supplier_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Document',
                'verbose_name_plural': 'Supplier Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
