# Generated by Django 5.2.4 on 2025-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_senderinformation_senderemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderemail',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='smtp_encryption',
            field=models.CharField(choices=[('none', 'None'), ('ssl', 'SSL/TLS'), ('tls', 'STARTTLS')], default='tls', max_length=10),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='smtp_host',
            field=models.CharField(default='', help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password or app-specific password', max_length=255),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (e.g., 587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='smtp_username',
            field=models.CharField(default='', help_text='SMTP username (often same as email)', max_length=255),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='verification_error',
            field=models.TextField(blank=True),
        ),
    ]
