# Generated by Django 5.2.4 on 2025-08-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_senderemail_last_verified_and_more'),
        ('customer', '0007_remove_customer_organization_remove_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to (admin only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='customer.organization'),
        ),
    ]
