# Generated by Django 5.2.4 on 2025-08-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('product', '0009_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
