# Generated by Django 5.2.4 on 2025-08-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoporderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ShopOrder',
        ),
        migrations.DeleteModel(
            name='ShopOrderItem',
        ),
    ]
