# Generated by Django 5.2.4 on 2025-08-01 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_senderemail_last_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Template name for internal reference', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('sender_name', models.CharField(blank=True, help_text='Optional: Override sender name for this template', max_length=100)),
                ('content_type', models.CharField(choices=[('plain', 'Plain Text'), ('html', 'HTML'), ('both', 'Both HTML and Plain Text')], default='both', help_text='Email content format', max_length=10)),
                ('html_content', models.TextField(blank=True, help_text='HTML version of the email content')),
                ('plain_content', models.TextField(blank=True, help_text='Plain text version of the email content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_variables', models.JSONField(blank=True, default=dict, help_text='Available template variables and their descriptions')),
                ('track_opens', models.BooleanField(default=True, help_text='Track email opens')),
                ('track_clicks', models.BooleanField(default=True, help_text='Track link clicks')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
                ('sender_email', models.ForeignKey(blank=True, help_text='Select the sender email address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.senderemail')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='email_templ_status_45e5b5_idx')],
            },
        ),
    ]
