# Generated by Django 5.2.4 on 2025-08-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variable name (e.g., 'customer_name', 'discount_code')", max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('url', 'URL'), ('email', 'Email'), ('boolean', 'Boolean'), ('choice', 'Choice')], default='text', help_text='Variable data type', max_length=20)),
                ('length', models.PositiveIntegerField(blank=True, help_text='Maximum length for text/url/email types', null=True)),
                ('description', models.CharField(blank=True, help_text='Description of what this variable represents', max_length=200)),
                ('default_value', models.CharField(blank=True, help_text='Default value if not provided', max_length=500)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this variable must be provided')),
                ('choices', models.JSONField(blank=True, default=list, help_text="Available choices for 'choice' type variables")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['template', 'name'], name='email_templ_templat_c34cbb_idx')],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
