# Generated by Django 5.2.4 on 2025-08-16 16:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('customer', '0010_add_financial_account'),
        ('purchases', '0005_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(help_text='Auto-generated expense number', max_length=50, unique=True)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rent', 'Rent & Lease'), ('utilities', 'Utilities'), ('salaries', 'Salaries & Wages'), ('insurance', 'Insurance'), ('supplies', 'Office Supplies'), ('marketing', 'Marketing & Advertising'), ('travel', 'Travel & Entertainment'), ('professional', 'Professional Services'), ('maintenance', 'Repairs & Maintenance'), ('depreciation', 'Depreciation'), ('taxes', 'Taxes & Licenses'), ('interest', 'Interest Expense'), ('other', 'Other Expenses')], help_text='Type of expense', max_length=20)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, help_text='Invoice number, receipt number, etc.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total including tax', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('posted', 'Posted to Ledger'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('receipt_file', models.FileField(blank=True, help_text='Upload receipt or invoice', null=True, upload_to='expenses/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='customer.organization')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(blank=True, help_text='Expense account to debit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='accounting.ledgeraccount')),
                ('financial_account', models.ForeignKey(blank=True, help_text='Account used for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='customer.financialaccount')),
                ('vendor', models.ForeignKey(blank=True, help_text='Link to supplier if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'expense_date'], name='accounting__company_12e032_idx'), models.Index(fields=['status'], name='accounting__status_198e00_idx'), models.Index(fields=['category'], name='accounting__categor_2b41ab_idx')],
            },
        ),
    ]
