# Generated by Django 5.2.4 on 2025-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_email_invoice_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='post_tracking_number',
            field=models.CharField(blank=True, help_text='For shop orders with shipping', max_length=50),
        ),
    ]
