# Generated by Django 5.2.4 on 2025-08-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_post_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_service',
            field=models.CharField(blank=True, choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other')], help_text='Shipping service for shop orders', max_length=20, null=True),
        ),
    ]
