# Generated by Django 5.2.4 on 2025-08-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_delivery_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
