# Generated by Django 5.2.4 on 2025-08-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_change_user_related_name'),
        ('sales', '0006_invoiceitem_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customer.customer'),
        ),
    ]
