# Generated by Django 5.2.4 on 2025-08-10 18:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaseorder_shipping_address_line1_and_more'),
        ('sales', '0008_invoice_shipping_status_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='delivery_service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='post_tracking_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', help_text='Shipping status for shop orders', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unsent', 'Unsent'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partial', 'Partial'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(help_text='Human-readable shipment number', max_length=50, unique=True)),
                ('carrier', models.CharField(choices=[('ups', 'UPS'), ('fedex', 'FedEx'), ('usps', 'USPS'), ('dhl', 'DHL'), ('amazon', 'Amazon Logistics'), ('internal', 'Internal Delivery'), ('pickup', 'Customer Pickup'), ('other', 'Other')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Carrier tracking number', max_length=255)),
                ('tracking_url', models.URLField(blank=True, help_text='Direct link to track this shipment')),
                ('service_type', models.CharField(blank=True, help_text='e.g., Ground, 2-Day Air, Overnight', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery Attempt'), ('returned', 'Returned to Sender'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('package_count', models.PositiveIntegerField(default=1, help_text='Number of packages in this shipment')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in pounds', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_date', models.DateTimeField(blank=True, help_text='When the package was shipped', null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Estimated delivery date/time', null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, help_text='Actual delivery date/time', null=True)),
                ('delivered_to', models.CharField(blank=True, help_text='Name of person who received the package', max_length=255)),
                ('delivery_signature', models.TextField(blank=True, help_text='Signature data or confirmation code')),
                ('delivery_notes', models.TextField(blank=True, help_text='Delivery instructions or notes')),
                ('ship_to_name', models.CharField(max_length=255)),
                ('ship_to_company', models.CharField(blank=True, max_length=255)),
                ('ship_to_address_line1', models.CharField(max_length=255)),
                ('ship_to_address_line2', models.CharField(blank=True, max_length=255)),
                ('ship_to_city', models.CharField(max_length=100)),
                ('ship_to_state', models.CharField(max_length=50)),
                ('ship_to_postal_code', models.CharField(max_length=20)),
                ('ship_to_country', models.CharField(default='US', max_length=2)),
                ('ship_to_phone', models.CharField(blank=True, max_length=50)),
                ('ship_to_email', models.EmailField(blank=True, max_length=254)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about this shipment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.invoice')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier shipping these items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_shipments', to='purchases.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('serial_numbers', models.JSONField(blank=True, default=list, help_text='List of serial numbers for items in this shipment')),
                ('notes', models.TextField(blank=True, help_text='Notes about this item in the shipment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='sales.invoiceitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoiceshipment')),
            ],
            options={
                'ordering': ['invoice_item__id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoiceshipment',
            index=models.Index(fields=['invoice', 'status'], name='sales_invoi_invoice_c7ea61_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceshipment',
            index=models.Index(fields=['tracking_number'], name='sales_invoi_trackin_c6e7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceshipment',
            index=models.Index(fields=['supplier', 'status'], name='sales_invoi_supplie_e5d216_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'invoice_item')},
        ),
    ]
