# Generated by Django 5.2.4 on 2025-08-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_invoice_delivery_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
