# Generated by Django 5.2.4 on 2025-08-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_invoice_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
