# Generated by Django 5.2.4 on 2025-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_fix_tax_and_discount_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accounting_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', help_text='Accounting status for invoices', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
