# Generated by Django 5.2.4 on 2025-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoice_accounting_status_invoice_is_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accounting_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', help_text='Accounting status for invoices', max_length=20),
        ),
    ]
