# Generated by Django 5.2.4 on 2025-08-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_add_financial_account'),
        ('sales', '0013_alter_invoice_accounting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Financial account used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customer.financialaccount'),
        ),
    ]
